### ISSUE TITLE
Internal Server Error in Config

### ISSUE THREAD

**Issue by Seculin** [inteos/IBAdmin#15]
Hello Team, 

I just installed the latest version of Bacula  community(9.6.3) with IBADMIN

Everything works well, but when i go to /system/config/ I have a 500 error

here is the stack trace in apache log.Is it an issue with the version of Bacula community ?

`[Mon Mar 16 07:47:46.372432 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860] mod_wsgi (pid=14930): Exception occurred processing WSGI script '/opt/ibadmin/ibadmin/wsgi.py'.
[Mon Mar 16 07:47:46.372490 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860] Traceback (most recent call last):
[Mon Mar 16 07:47:46.372511 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 170, in __call__
[Mon Mar 16 07:47:46.372543 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     response = self.get_response(request)
[Mon Mar 16 07:47:46.372567 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 124, in get_response
[Mon Mar 16 07:47:46.372589 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     response = self._middleware_chain(request)
[Mon Mar 16 07:47:46.372596 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 44, in inner
[Mon Mar 16 07:47:46.372616 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     response = response_for_exception(request, exc)
[Mon Mar 16 07:47:46.372623 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 94, in response_for_exception
[Mon Mar 16 07:47:46.372640 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
[Mon Mar 16 07:47:46.372652 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 132, in handle_uncaught_exception
[Mon Mar 16 07:47:46.372673 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     extra={'status_code': 500, 'request': request},
[Mon Mar 16 07:47:46.372684 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
[Mon Mar 16 07:47:46.372705 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     self._log(ERROR, msg, args, **kwargs)
[Mon Mar 16 07:47:46.372720 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
[Mon Mar 16 07:47:46.372742 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     self.handle(record)
[Mon Mar 16 07:47:46.372755 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
[Mon Mar 16 07:47:46.372791 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     self.callHandlers(record)
[Mon Mar 16 07:47:46.372805 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
[Mon Mar 16 07:47:46.372827 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     hdlr.handle(record)
[Mon Mar 16 07:47:46.372840 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
[Mon Mar 16 07:47:46.372862 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     self.emit(record)
[Mon Mar 16 07:47:46.372878 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/dist-packages/django/utils/log.py", line 121, in emit
[Mon Mar 16 07:47:46.372902 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     self.send_mail(subject, message, fail_silently=True, html_message=html_message)
[Mon Mar 16 07:47:46.372917 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/dist-packages/django/utils/log.py", line 124, in send_mail
[Mon Mar 16 07:47:46.372942 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
[Mon Mar 16 07:47:46.372955 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/dist-packages/django/core/mail/__init__.py", line 103, in mail_admins
[Mon Mar 16 07:47:46.372979 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     mail.send(fail_silently=fail_silently)
[Mon Mar 16 07:47:46.372995 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/dist-packages/django/core/mail/message.py", line 342, in send
[Mon Mar 16 07:47:46.373015 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     return self.get_connection(fail_silently).send_messages([self])
[Mon Mar 16 07:47:46.373028 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
[Mon Mar 16 07:47:46.373053 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     new_conn_created = self.open()
[Mon Mar 16 07:47:46.373069 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 58, in open
[Mon Mar 16 07:47:46.373091 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     self.connection = connection_class(self.host, self.port, **connection_params)
[Mon Mar 16 07:47:46.373105 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
[Mon Mar 16 07:47:46.373128 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     (code, msg) = self.connect(host, port)
[Mon Mar 16 07:47:46.373143 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/smtplib.py", line 316, in connect
[Mon Mar 16 07:47:46.373166 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     self.sock = self._get_socket(host, port, self.timeout)
[Mon Mar 16 07:47:46.373179 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
[Mon Mar 16 07:47:46.373197 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     return socket.create_connection((host, port), timeout)
[Mon Mar 16 07:47:46.373212 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
[Mon Mar 16 07:47:46.373242 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860]     raise err
[Mon Mar 16 07:47:46.373275 2020] [wsgi:error] [pid 14930:tid 140608924489472] [client XXX.XXX.XX.XX:54860] error: [Errno 111] Connection refused`

Thank you

**Comment by rkorzeniewski** [comment]
Hello Seculin,

I'm sorry that you've got a 500 error with IBAdmin. Unfortunate the apache log you attached confirm wsgi error but do not disclose the root cause of the issue. Generally you should get an email from IBAdmin with all the details we need to diagnose the issue. But it seems that your smtp server refused to connect.
You can resolve smtp server issue first and recreate the issue with /system/config/ then attach the content of the email here.
Or you can run IBAdmin with Debug mode. To do it, you should change DEBUG flag in your ibadmin/settings.py file:
```
DEBUG = True
```
then manually execute application with the following command:
```
source /opt/ibadengine/bin/activate
/opt/ibadmin/manage.py runserver <ipaddress>:<port>
```
where `ipaddress` is the address of your server and `port` is the port number application will respond. You can use the same ip/port of your current apache server if you shutdown your apache server first. Else you have to change at least the port number.
Then recreate the issue with /system/config/ and on your terminal you should get required traceback. This is all we need to diagnose the issue.
Thank you for using IBAdmin. I hope we could resolve the issue soon.

**Comment by Seculin** [comment]
thank you for you help ! 

Here is the logs https://pastebin.com/9M5BfsHS
